# Generated by Django 2.2.7 on 2019-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.TextField(max_length=300)),
                ('rank', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
    ]
