# Generated by Django 2.2.7 on 2019-12-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=50),
        ),
    ]
