# Generated by Django 2.2.7 on 2019-12-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_address', models.CharField(max_length=200)),
            ],
        ),
    ]
